'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
            If My.Application.SaveMySettingsOnExit Then
                My.Settings.Save()
            End If
        End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

#Region "Discord"
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property Discord() As String
            Get
                Return CType(Me("Discord"), String)
            End Get
            Set
                Me("Discord") = Value
            End Set
        End Property
#End Region

#Region "Rocket League"
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property RLRankOnes() As String
            Get
                Return CType(Me("RLRankOnes"), String)
            End Get
            Set
                Me("RLRankOnes") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property RLRankTwos() As String
            Get
                Return CType(Me("RLRankTwos"), String)
            End Get
            Set
                Me("RLRankTwos") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property RLRankThrees() As String
            Get
                Return CType(Me("RLRankThrees"), String)
            End Get
            Set
                Me("RLRankThrees") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property RLRankSoloThrees() As String
            Get
                Return CType(Me("RLRankSoloThrees"), String)
            End Get
            Set
                Me("RLRankSoloThrees") = Value
            End Set
        End Property
#End Region

#Region "Roulette"
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ViewerRouletteOdds() As Integer
            Get
                Return CType(Me("ViewerRouletteOdds"), Integer)
            End Get
            Set
                Me("ViewerRouletteOdds") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property SubRouletteOdds() As Integer
            Get
                Return CType(Me("SubRouletteOdds"), Integer)
            End Get
            Set
                Me("SubRouletteOdds") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ViewerRouletteMultiplier() As Integer
            Get
                Return CType(Me("ViewerRouletteMultiplier"), Integer)
            End Get
            Set
                Me("ViewerRouletteMultiplier") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property SubRouletteMultiplier() As Integer
            Get
                Return CType(Me("SubRouletteMultiplier"), Integer)
            End Get
            Set
                Me("SubRouletteMultiplier") = Value
            End Set
        End Property
#End Region

#Region "Garlic Bread"
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ViewerGarlicBreadOdds() As Integer
            Get
                Return CType(Me("ViewerGarlicBreadOdds"), Integer)
            End Get
            Set
                Me("ViewerGarlicBreadOdds") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property SubGarlicBreadOdds() As Integer
            Get
                Return CType(Me("SubGarlicBreadOdds"), Integer)
            End Get
            Set
                Me("SubGarlicBreadOdds") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ViewerGarlicBreadMultiplier() As Integer
            Get
                Return CType(Me("ViewerGarlicBreadMultiplier"), Integer)
            End Get
            Set
                Me("ViewerGarlicBreadMultiplier") = Value
            End Set
        End Property
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property SubGarlicBreadMultiplier() As Integer
            Get
                Return CType(Me("SubGarlicBreadMultiplier"), Integer)
            End Get
            Set
                Me("SubGarlicBreadMultiplier") = Value
            End Set
        End Property
#End Region

#Region "Slots"
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ViewerSlotsOdds() As Integer
            Get
                Return CType(Me("ViewerSlotsOdds"), Integer)
            End Get
            Set
                Me("ViewerSlotsOdds") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property SubSlotsOdds() As Integer
            Get
                Return CType(Me("SubSlotsOdds"), Integer)
            End Get
            Set
                Me("SubSlotsOdds") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ViewerSlotsMultiplier() As Integer
            Get
                Return CType(Me("ViewerSlotsMultiplier"), Integer)
            End Get
            Set
                Me("ViewerSlotsMultiplier") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property SubSlotsMultiplier() As Integer
            Get
                Return CType(Me("SubSlotsMultiplier"), Integer)
            End Get
            Set
                Me("SubSlotsMultiplier") = Value
            End Set
        End Property
#End Region

#Region "IRC Connection Details"
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property TwitchRemember() As Boolean
            Get
                Return CType(Me("TwitchRemember"), Boolean)
            End Get
            Set
                Me("TwitchRemember") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property TwitchUser() As String
            Get
                Return CType(Me("TwitchUser"), String)
            End Get
            Set
                Me("TwitchUser") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property TwitchOAuth() As String
            Get
                Return CType(Me("TwitchOAuth"), String)
            End Get
            Set
                Me("TwitchOAuth") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property TwitchChannel() As String
            Get
                Return CType(Me("TwitchChannel"), String)
            End Get
            Set
                Me("TwitchChannel") = Value
            End Set
        End Property
#End Region

#Region "Command Prefix"
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property CommandPrefix() As String
            Get
                Return CType(Me("CommandPrefix"), String)
            End Get
            Set
                Me("CommandPrefix") = Value
            End Set
        End Property
#End Region

#Region "Boopie Timed Payments"
        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property BoopieDelay() As Integer
            Get
                Return CType(Me("BoopieDelay"), Integer)
            End Get
            Set
                Me("BoopieDelay") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ViewerBoopiePayout() As Integer
            Get
                Return CType(Me("ViewerBoopiePayout"), Integer)
            End Get
            Set
                Me("ViewerBoopiePayout") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property SubBoopiePayout() As Integer
            Get
                Return CType(Me("SubBoopiePayout"), Integer)
            End Get
            Set
                Me("SubBoopiePayout") = Value
            End Set
        End Property
#End Region

    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.BoopieBot.My.MySettings
            Get
                Return Global.BoopieBot.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
